# %% [markdown]
# # Reproduce every MutPred-PPI figure and table, from scratch
#
# Runner notebook for the MutPred-PPI publication repo. Given the Zenodo
# deposit (`datasets/`, `weights/`) it regenerates, in order: stability
# pretraining -> the canonical data layer and contact-graph store ->
# embeddings for every method -> group cross-validation (GCV) -> the
# VarChAMP blind test -> the final all-data model -> variant-repository
# inference -> every manuscript figure and table.
#
# **Caching.** Every step checks whether its output already exists before
# doing anything, so a second run of the whole notebook with `FORCE=False`
# finishes in well under a minute. Embedding/GCV/inference scripts also
# resume by content key internally, so re-running one is cheap even after a
# partial failure.
#
# **QUICK mode.** `QUICK=True` runs 1 GCV seed (not 30), subsamples the
# variant databases, and shrinks the enrichment bootstraps -- the whole
# pipeline finishes in hours instead of the days a full run takes, for
# smoke-testing the chain. **Quick-mode output never touches the canonical
# `results/` tree that `figures/*.png` symlink into** -- it is redirected to
# a sandbox via `MUTPRED_PPI_RESULTS_DIR` (see `src/paths.py`).
#
# **Only `datasets/training_eval/` data is ever read.** Every dataset name is
# one of the five `*_mapped090826` configs in `utils.gcv_common.DATASET_CONFIGS`;
# `utils.legacy_guard` raises rather than silently accepting anything from the
# retired pre-090826 pipeline (`.mat`/`.pos`/`.neg`/`.labels`/`.vt_ids` files,
# `all_vt_ids_and_labels.txt`, `sfvcfp_rows.csv.gz`, `training_data_internal.csv`,
# ...). See the per-step comments below for the full inventory this notebook
# was built to satisfy, and `docs/REPRODUCING_ANALYSES.md` for the underlying
# per-script commands this notebook wraps.
#
# AF3 structures are complete: 100,739 canonical complexes, 100% training/eval
# coverage. 24,716 are in-house AlphaFold 3 predictions; the rest come from
# ProtVar (see the structure step below).
#
# **Not reproducible here, by design:**
# Fig 4/S2 and Table 1 need unpublished VarChAMP data, present only in
# `datasets/training_eval/varchamp_all_mapped090826_rows.csv.gz`; those steps
# detect its absence and skip with a clear message rather than failing. Figs
# 1 and 2 (pipeline, architecture) and the CDC42 example panel are drawn by
# hand and are not regenerated by anything in this repo.

# %% Configuration
import os
from pathlib import Path

# QUICK is the SHIPPED DEFAULT and does NOT reproduce the paper: 1 cross-validation
# seed instead of 30, subsampled variant databases, small bootstraps. It exists so a
# first run finishes in hours and proves the environment works, and it writes to
# results_quick/ so it cannot overwrite a real run. Set False for the published numbers.
QUICK = True
FORCE = False          # recompute even when a cached output already exists
DEVICE = "cuda:0"
RUN_PRETRAIN = False    # Step 1; off by default, uses the deposited checkpoint
RUN_MUTPRED2 = False    # Step 4b/6; MutPred2 runs off-machine, off by default
# Step 2b: rebuild the BioGRID interactome and the per-database variant mappings
# from raw downloads. Off by default because the Zenodo bundle already ships what
# they produce (datasets/variant_dbs/*_rows.csv.gz), and the inputs are licensed
# (COSMIC, HGMD) or many-GB (ClinVar, gnomAD, BioGRID). Turn on only to rederive
# the interactome from source.
RUN_VARIANT_DB_MAPPING = False
DRY_RUN = False         # print commands instead of executing them

REPO = Path(__file__).resolve().parent.parent if "__file__" in dir() else Path.cwd().parent
os.chdir(REPO)

N_GCV = 1 if QUICK else 30
N_BOOTSTRAP = 1_000 if QUICK else 100_000

# Extra figures for talks rather than the paper. Off by default: they are
# not referenced by the manuscript and cost a step each.
PRESENTATION_FIGURES = False
DB_SUBSAMPLE = 20_000 if QUICK else None   # rows per variant DB; None = all

# Every results/<subdir> constant in src/paths.py derives from this one env
# var (see src/paths.py's MUTPRED_PPI_RESULTS_DIR docstring), so setting it
# before any src/ import redirects the *entire* results/ tree at once.
_RESULTS_DIR = REPO / "results_quick" if QUICK else REPO / "results"
os.environ["MUTPRED_PPI_RESULTS_DIR"] = str(_RESULTS_DIR)

print(f"QUICK={QUICK}  FORCE={FORCE}  DEVICE={DEVICE}")
print(f"Results root: {_RESULTS_DIR}"
      + ("  (sandbox -- canonical results/ untouched)" if QUICK else "  (canonical)"))

# %% Shared helpers
import subprocess
import sys
import time

import pandas as pd
from IPython.display import Image, display

sys.path.insert(0, str(REPO / "src"))
from paths import (CONTACT_GRAPH_STORE, DATA_ROOT, DATASETS_DIR,  # noqa: E402
                   REPO_ROOT, TRAINING_EVAL_DIR, WEIGHTS_DIR, describe)
from utils.gcv_common import dataset_name  # noqa: E402
from utils.legacy_guard import LegacyInputError, reject_legacy  # noqa: E402

_ENV = {**os.environ, "MPLBACKEND": "Agg", "OPENBLAS_NUM_THREADS": "1"}


def graph_store_is_stale(store_path, manifest_path) -> bool:
    """True if the contact-graph store does not cover every canonical structure.

    Existence is not freshness. `produces=` only asks whether an output file is
    there, which is right for a pure function of fixed inputs and wrong for any
    artifact whose inputs GROW. The contact-graph store is the sharp case: it is
    derived from `af3_structures_canonical/`, which gains structures every time a
    batch of AlphaFold3 jobs is folded and merged in.

    The comparison is on KEY IDENTITY, not counts. Both the store and the
    manifest are keyed by the sorted pair of `sha256(sequence)[:16]` hashes, so
    the check is exact and cheap. Counting alone is not enough and was briefly
    wrong here once: a store can hold the same NUMBER of graphs as the manifest
    has rows while missing some structures and carrying others that were
    removed.
    """
    import csv as _csv
    import h5py as _h5py
    store_path, manifest_path = Path(store_path), Path(manifest_path)
    if not store_path.exists() or not manifest_path.exists():
        return False                      # nothing to compare; `produces` decides
    try:
        with _h5py.File(store_path, "r") as f:
            have = set(f["graphs"].keys()) if "graphs" in f else set()
        want = set()
        with open(manifest_path) as f:
            for row in _csv.DictReader(f):
                a, b = row["seq_a_sha"], row["seq_b_sha"]
                want.add("_".join(sorted((a, b))))
    except Exception as exc:              # unreadable store -> rebuild it
        print(f"[stale]   {store_path.name}: unreadable ({exc}) -- will rebuild")
        return True
    missing = want - have
    if missing:
        print(f"[stale]   {store_path.name}: {len(missing)} of {len(want)} "
              f"canonical structures have no graph -- rebuilding")
        return True
    return False


def run(cmd: list, *, produces: list | None = None, name: str | None = None,
       cwd: Path | None = None, stale: bool = False,
       requires: list | None = None) -> None:
    """Run a command, skipping it if every `produces` path already exists.

    This is the whole caching layer: a second notebook run with
    `FORCE=False` finds every `produces` path present and does nothing.

    `stale=True` overrides that skip for artifacts whose inputs can grow -- see
    `graph_store_is_stale`. Existence-only caching is correct for a pure function
    of fixed inputs and silently wrong for anything else.

    `requires` names inputs the reader may legitimately not have -- a licensed or
    bulk download. A missing one SKIPS the step with a message naming the file,
    rather than failing the notebook, because the artifact it would rebuild is
    already in the Zenodo bundle.
    """
    label = name or Path(str(cmd[2]) if len(cmd) > 2 else cmd[0]).name
    produces = [Path(p) for p in (produces or [])]
    if produces and not FORCE and not stale and all(p.exists() for p in produces):
        print(f"[cached]  {label}  ({len(produces)} output(s) present)")
        return
    absent = [Path(r) for r in (requires or []) if not Path(r).exists()]
    if absent:
        print(f"[skip]    {label}  (needs {absent[0]})")
        return
    print(f"[run]     {label}")
    print(f"          {' '.join(str(c) for c in cmd)}")
    if DRY_RUN:
        return
    t0 = time.time()
    result = subprocess.run(cmd, cwd=str(cwd or REPO), env=_ENV,
                            capture_output=True, text=True)
    dt = time.time() - t0
    tail = "\n".join(result.stdout.splitlines()[-20:])
    print(tail)
    if result.returncode != 0:
        print(result.stderr[-4000:])
        raise RuntimeError(f"{label} failed (exit {result.returncode}) after {dt:.0f}s")
    print(f"          done in {dt:.0f}s")


def show(path, caption: str = "") -> None:
    """Display a figure inline; warn (don't raise) if it isn't there yet."""
    path = Path(path)
    if not path.exists():
        print(f"[missing] {caption or path.name}: {path}")
        return
    print(f"{caption or path.name}  ->  {path}")
    display(Image(filename=str(path)))


def assert_fresh(*paths) -> None:
    """Refuse pre-090826 artifacts -- thin wrapper over utils.legacy_guard."""
    reject_legacy(*paths)


def subsample_rows(db: str, n: int, seed: int = 0) -> Path:
    """A seeded subsample of a variant-DB row table, for QUICK-mode --rows."""
    src = DATASETS_DIR / "variant_dbs" / f"{db}_rows.csv.gz"
    out_dir = _RESULTS_DIR / "_quick_subsamples"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{db}_rows_n{n}.csv.gz"
    if out.exists() and not FORCE:
        return out
    df = pd.read_csv(src)
    df.sample(n=min(n, len(df)), random_state=seed).to_csv(out, index=False)
    return out


PY = sys.executable

# %% [markdown]
# ## Step 0 -- Preflight
#
# Installs the package, prints every resolved path (`src/paths.py::describe()`),
# and checks the tools cross-validation needs.

# %%
run([PY, "-m", "pip", "install", "-e", "."], name="pip install -e .")
print(describe())

# %%
import shutil

if shutil.which("cd-hit") is None:
    print("[note] cd-hit not on PATH -- only needed to rebuild splits from "
          "scratch; datasets/cv_reference/ ships the published splits, so "
          "GCV does not need it for a normal run.")
else:
    print(f"cd-hit: {shutil.which('cd-hit')}")

import torch
print(f"CUDA available: {torch.cuda.is_available()}  "
      f"device count: {torch.cuda.device_count() if torch.cuda.is_available() else 0}")

# %% [markdown]
# ## Step 1 -- Stability pretraining (optional)
#
# Off by default: the deposited `weights/MutPred-PPI_stability_pretrain.pt`
# is what every fine-tuned model starts from. Set `RUN_PRETRAIN = True` to
# regenerate it from raw sources -- download
# `Tsuboyama2023_Dataset2_Dataset3_20230416.csv` and `AlphaFold_model_PDBs.zip`
# from <https://zenodo.org/records/7992926> first.

# %%
_STABILITY_CKPT = WEIGHTS_DIR / "MutPred-PPI_stability_pretrain.pt"

if not RUN_PRETRAIN:
    if _STABILITY_CKPT.exists():
        print(f"[cached]  using deposited checkpoint: {_STABILITY_CKPT}")
    else:
        print(f"[missing] {_STABILITY_CKPT} -- set RUN_PRETRAIN=True, or "
              f"deposit weights/MutPred-PPI_stability_pretrain.pt")
else:
    _MEGASCALE_CSV = DATA_ROOT / "Tsuboyama2023_Dataset2_Dataset3_20230416.csv"
    _MEGASCALE_PDBS = DATA_ROOT / "AlphaFold_model_PDBs"
    _MEGASCALE_OUT = REPO / "megascale_preprocessed"
    for p in (_MEGASCALE_CSV, _MEGASCALE_PDBS):
        if not p.exists():
            raise FileNotFoundError(
                f"{p} not found. Download from https://zenodo.org/records/7992926 "
                f"(Tsuboyama2023_Dataset2_Dataset3_20230416.csv, AlphaFold_model_PDBs.zip) "
                f"and place under {DATA_ROOT}.")
    run([PY, "src/training/preprocess_stability_data.py",
        "--csv", str(_MEGASCALE_CSV), "--pdb-dir", str(_MEGASCALE_PDBS),
        "--splits", str(DATASETS_DIR / "mega_splits.pkl"),
        "--outdir", str(_MEGASCALE_OUT), "--device", DEVICE, "--n-jobs", "16"],
       produces=[_MEGASCALE_OUT / "preprocessed.pkl",
                 _MEGASCALE_OUT / "mutation_diff_scaler.pkl"],
       name="preprocess_stability_data.py")
    run([PY, "src/training/pretrain_stability.py",
        "--data", str(_MEGASCALE_OUT / "preprocessed.pkl"),
        "--scaler", str(_MEGASCALE_OUT / "mutation_diff_scaler.pkl"),
        "--outmodel", str(_STABILITY_CKPT), "--device", DEVICE],
       produces=[_STABILITY_CKPT], name="pretrain_stability.py")

# %% [markdown]
# ## Step 2 -- Canonical data layer and caches
#
# Structures -> contact graphs -> canonical row tables -> CV reference
# splits -> the small annotation caches every figure script reads. Every
# output here is content-addressed or dataset-scoped, so re-running with
# `FORCE=False` is a no-op once built.

# %%
_AF3_CANON = DATASETS_DIR / "af3_structures_canonical"
_MAPPED = TRAINING_EVAL_DIR
_STORE = CONTACT_GRAPH_STORE

# ONE canonical structure tree and ONE graph store. Training/evaluation
# complexes and variant-repository complexes share both: graphs are keyed by
# sequence, so a pair that appears in each is stored once. Keeping two trees
# would mean the same complex could be folded differently on either side.
#
# Variant-repository complexes come from the in-house foldings AND from ProtVar's
# precomputed AlphaFold 3 interfaces, which supply about three quarters of the
# canonical tree (76,023 of 100,739 structures). Chains are resolved by SEQUENCE,
# so the whole ProtVar tree can be passed unfiltered; PDB input is auto-detected
# and normalised to gzipped mmCIF. See docs/DATA.md for the download.
_PROTVAR = REPO / "external" / "protvar_pdb"
_STRUCT_SOURCES = [str(DATASETS_DIR / "af3_structures"),
                   str(DATASETS_DIR / "af3_structures_variant_dbs")]
if _PROTVAR.exists():
    _STRUCT_SOURCES.append(str(_PROTVAR))
else:
    print(f"[warn]    {_PROTVAR} absent -- the variant repositories will lose the "
          f"pairs only ProtVar covers (see docs/DATA.md)")

run([PY, "src/data_processing/canonicalize_structures.py",
    "--structures", *_STRUCT_SOURCES, "--out", str(_AF3_CANON)],
   produces=[_AF3_CANON / "manifest.csv"], name="canonicalize_structures.py")

run([PY, "src/data_processing/rebuild_graphs_from_structures.py",
    "--structures", str(_AF3_CANON), "--out", str(_STORE)],
   produces=[_STORE],
   stale=graph_store_is_stale(_STORE, _AF3_CANON / "manifest.csv"),
   name="rebuild_graphs_from_structures.py")

# Record which complexes AlphaFold3 actually produced. Writes an `af3_failed`
# column into the mapping CSVs; `prepare_gcv_tables.py` then drops those rows
# before assigning row_index, so nothing downstream ever scores a complex with
# no contact graph. Must run AFTER canonicalize_structures.py and BEFORE
# prepare_gcv_tables.py.
run([PY, "src/data_processing/annotate_af3_coverage.py"],
   name="annotate_af3_coverage.py")

# The GCV row/split tables. Stage 2 of the data-preparation chain: reads the
# mapping CSVs in datasets/source_mapping/ (built by
# notebooks/map_ppi_datasets.py) and writes datasets/training_eval/.
# Must run BEFORE prepare_af3_inputs.py, which derives its required-pair set
# from these tables. Moved here from repro_test/build_canonical_tables.py and
# renamed 2026-09-10 -- the old name was ambiguous with the mapping notebook,
# and it lived in a gitignored directory. See docs/DATA_PREPARATION.md.
run([PY, "src/data_processing/training_sets/prepare_gcv_tables.py",
    "--n-seeds", str(N_GCV)],
   produces=[_MAPPED / f'{dataset_name("sahni_fragoza")}_rows.csv.gz'],
   name="prepare_gcv_tables.py")

# Prepares AlphaFold3 inputs for every complex not already folded (required =
# union of all five canonical datasets, since the pooled
# sahni_fragoza_varchamp_all can drop a conflicting row that is still valid,
# unconflicted data in a smaller dataset). Exits cleanly when nothing is
# missing. Does not gate anything below: rows without a structure are excluded
# by the shared per-class AUC wherever they turn up. Folding the emitted JSONs
# is a manual, off-box step -- see docs/DATA_PREPARATION.md.
run([PY, "src/data_processing/prepare_af3_inputs.py"],
   name="prepare_af3_inputs.py")
if not RUN_VARIANT_DB_MAPPING:
    print("[skip]    BioGRID interactome + per-database mapping "
          "(RUN_VARIANT_DB_MAPPING=False; the shipped row tables already "
          "encode them)")

# The BioGRID direct-binding interactome is stage 0 of the variant-database
# chain: every map_*.py draws its partners from these pickles, and every pair in
# the row tables below is one of its edges. "Physical binding evidence only"
# means the five experimental systems in
# get_biogrid_interactors.BINDING_TECHNIQUES -- Co-crystal Structure,
# Cross-Linking-MS, Far Western, Reconstituted Complex, Protein-Peptide --
# excluding co-complex-membership assays, because an edgotype is a claim about a
# specific binding interface. Needs the BioGRID download, so it is skipped (not
# failed) when that is absent; the shipped row tables already encode its result.
if RUN_VARIANT_DB_MAPPING:
    _BIOGRID = DATA_ROOT / "biogrid"
    run([PY, "src/data_processing/variant_databases/get_biogrid_interactors.py",
        "--biogrid-tsv", str(_BIOGRID / "biogrid_ppi.tsv"),
        "--uniprot-fasta", str(_BIOGRID / "all_uniprot_ids.fasta"),
        "--output-dir", str(_BIOGRID)],
       produces=[_BIOGRID / "biogrid_dirbind_uniprot_to_interactors.pkl"],
       requires=[_BIOGRID / "biogrid_ppi.tsv"],
       name="get_biogrid_interactors.py (physical-binding interactome)")

    # Stage 1: per-database mapping. Each turns one raw download into the
    # UniProt-keyed variant/partner pickles `build_variant_db_tables.py` consumes,
    # drawing partners from the BioGRID interactome built above. Every one is
    # guarded by `requires`, because the raw inputs are licensed (COSMIC, HGMD) or
    # bulk downloads (ClinVar, gnomAD) that a reader may not hold -- a missing one
    # skips with the filename rather than failing the notebook, and the shipped
    # `datasets/variant_dbs/*_rows.csv.gz` already encode the result.
    _VDB = "src/data_processing/variant_databases"
    _ANN = DATASETS_DIR / "annotations"
    _ANNL = DATASETS_DIR / "annotations_licensed"

    run([PY, f"{_VDB}/map_clinvar.py", "--stage", "interactors",
        "--clinvar-dir", str(DATA_ROOT / "clinvar"), "--biogrid-dir", str(_BIOGRID),
        "--output-dir", str(_ANN / "clinvar")],
       produces=[_ANN / "clinvar" / "pathogenic_dirbind_variant_subset.pkl"],
       requires=[DATA_ROOT / "clinvar" / "pathogenic_wts_and_mts_04_25.fasta"],
       name="map_clinvar.py (interactors)")

    run([PY, f"{_VDB}/map_gnomad.py", "--biogrid-dir", str(_BIOGRID),
        "--gnomad-dir", str(DATA_ROOT / "gnomad"),
        "--output-dir", str(DATA_ROOT / "gnomad")],
       produces=[_ANN / "gnomad_allele_frequencies.tsv"],
       requires=[DATA_ROOT / "gnomad" / "gnomad_uniprot_wts.txt"],
       name="map_gnomad.py")

    run([PY, f"{_VDB}/get_cosmic_annotations.py", "--stage", "all",
        "--cmc-file", str(DATA_ROOT / "cosmic_mutations" /
                          "CancerMutationCensus_AllData_v101_GRCh37.tsv.gz"),
        "--output-dir", str(_ANNL)],
       produces=[_ANNL / "vt_to_tumor_site.pkl"],
       requires=[DATA_ROOT / "cosmic_mutations" /
                 "CancerMutationCensus_AllData_v101_GRCh37.tsv.gz"],
       name="get_cosmic_annotations.py (licensed)")

    run([PY, f"{_VDB}/map_hgmd.py", "--biogrid-dir", str(_BIOGRID),
        "--output-dir", str(_ANNL)],
       produces=[_ANNL / "hgmd_variant_subset.pkl"],
       requires=[DATA_ROOT / "hgmd" / "hgmd_dm_wts.fasta"],
       name="map_hgmd.py (licensed)")

    run([PY, f"{_VDB}/map_neurodev.py", "--mode", "neurodev",
        "--biogrid-dir", str(_BIOGRID),
        "--output-dir", str(DATA_ROOT / "neurodev")],
       produces=[_ANN / "neurodev" / "variant_label_dict.pkl"],
       requires=[DATA_ROOT / "neurodev" / "neurodev_case.fasta"],
       name="map_neurodev.py (NDD case/control)")

    run([PY, f"{_VDB}/map_asd_ndd.py",
        "--variant-dir", str(DATA_ROOT / "home" / "asd"),
        "--biogrid-dir", str(_BIOGRID),
        "--output-dir", str(DATA_ROOT / "home" / "asd")],
       produces=[DATA_ROOT / "home" / "asd" / "all_variants.pkl"],
       requires=[DATA_ROOT / "home" / "asd" / "Fu_variants_SebatLab.tsv"],
       name="map_asd_ndd.py (Fu et al. de novo ASD)")

run([PY, "src/variant_db_inference/build_variant_db_tables.py", "--db", "all"],
   produces=[DATASETS_DIR / "variant_dbs" / "clinvar_rows.csv.gz"],
   name="build_variant_db_tables.py")
run([PY, "src/analysis/export_cv_reference.py", "--dataset", "all", "--n-seeds", str(N_GCV)],
   produces=[DATASETS_DIR / "cv_reference" / "sahni_fragoza_train_rows.csv.gz"],
   name="export_cv_reference.py")

_ANNOT = DATASETS_DIR / "annotations"
run([PY, "src/analysis/build_plddt_cache.py",
    "--output", str(_ANNOT / "plddt_pair_cache.pkl"), "--force"],
   produces=[_ANNOT / "plddt_pair_cache.pkl"], name="build_plddt_cache.py")
run([PY, "src/analysis/build_confidence_cache.py",
    "--json-dir", str(DATA_ROOT), "--recursive",
    "--output", str(_ANNOT / "confidence_scores.pkl"), "--force"],
   produces=[_ANNOT / "confidence_scores.pkl"], name="build_confidence_cache.py")
run([PY, "src/analysis/build_ar_ad_gene_sets.py"],
   produces=[_ANNOT / "clingen_ar_ad_uniprot_sets.pkl"], name="build_ar_ad_gene_sets.py")
run([PY, "src/analysis/fetch_protein_class_annotations.py"],
   produces=[_RESULTS_DIR / "protein_class" / "protein_class_annotations.csv"],
   name="fetch_protein_class_annotations.py")

# %% [markdown]
# ## Step 3 -- Embeddings
#
# ProtT5 (MutPred-PPI), ESM-2 (eSIG-Net), MINT, PPLM -- one cache per dataset.
# QUICK mode covers `sahni_fragoza` only (Fig 3); full mode adds `sahni_only`
# (S2) and `sahni_fragoza_varchamp_all` (S6), plus `varchamp_all` for the
# blind test. SWING needs no precomputed cache -- Doc2Vec is fit per run.

# %%
_GCV_BASES = (["sahni_fragoza", "varchamp_all"] if QUICK
              else ["sahni_only", "sahni_fragoza",
                    "sahni_fragoza_varchamp_all", "varchamp_all"])
_GCV_DATASETS = [dataset_name(b) for b in _GCV_BASES]
_VARCHAMP_DATASET = dataset_name("varchamp_all")

for ds in _GCV_DATASETS:
    run([PY, "src/data_processing/precompute_prott5_datasets.py",
        "--dataset", ds, "--device", DEVICE],
       produces=[_MAPPED / f"{ds}_prott5.pkl"], name=f"precompute_prott5_datasets.py [{ds}]")
    run([PY, "src/data_processing/precompute_esm2_datasets.py",
        "--dataset", ds, "--device", DEVICE],
       produces=[_MAPPED / f"{ds}_esm2.pkl"], name=f"precompute_esm2_datasets.py [{ds}]")
    run([PY, "src/evaluation/precompute_mint_embeddings.py",
        "--dataset", ds, "--device", DEVICE, "--compute-residue"],
       produces=[_MAPPED / f"{ds}_mint.pkl"], name=f"precompute_mint_embeddings.py [{ds}]")
    run([PY, "src/evaluation/precompute_pplm_embeddings.py",
        "--dataset", ds, "--device", DEVICE],
       produces=[_MAPPED / f"{ds}_pplm.pkl"], name=f"precompute_pplm_embeddings.py [{ds}]")

# %% [markdown]
# ## Step 4 -- Group cross-validation (Fig 3, S3, S6)
#
# One command per method. `--n-gcv {N_GCV}` throughout (30 in a full run, 1
# in QUICK mode). MutPred-PPI, eSIG-Net, MINT x2, PPLM x2, SWING x2 are
# retrained per dataset; SAAMBE-3D/MutPPI/MutPPI+ are pretrained (SKEMPI) and
# just scored.
#
# **Note (2026-09-10):** `roc_plots.py`/`utils/gcv_common.py` were under
# active parallel development while this notebook was written (a
# `StaleCacheError` guard that validates GCV pkl row counts against the
# canonical table, more thorough than what this notebook alone provides). If
# Step 5 raises `StaleCacheError`, that guard is doing its job -- rerun the
# affected GCV command for that dataset, not this notebook.

# %%
_GCV_DIR = _RESULTS_DIR / "gcv"


def gcv_stem(method: str, dataset: str, *, ablation: str = "") -> str:
    tag = f"_{ablation}" if ablation else ""
    return f"{method}_{dataset}{tag}"


for ds in _GCV_DATASETS:
    if ds == _VARCHAMP_DATASET:
        continue  # blind-test target only, not a GCV training set
    run([PY, "src/evaluation/mutpred_ppi_gcv.py",
        "--dataset", ds, "--device", DEVICE, "--n-gcv", str(N_GCV)],
       produces=[_GCV_DIR / f"{gcv_stem('MutPredPPI', ds, ablation='megascale_all')}_detailed_results.pkl"],
       name=f"mutpred_ppi_gcv.py [{ds}]")
    run([PY, "src/evaluation/esignet_cv.py",
        "--dataset", ds, "--device", DEVICE, "--n-gcv", str(N_GCV)],
       produces=[_GCV_DIR / f"ESigNet_{ds}_detailed_results.pkl"], name=f"esignet_cv.py [{ds}]")
    for pred in ("seq_diff", "site_diff"):
        run([PY, "src/evaluation/mint_cv.py",
            "--dataset", ds, "--predictor", pred, "--n-gcv", str(N_GCV)],
           produces=[_GCV_DIR / f"MINT_{pred}_{ds}_detailed_results.pkl"],
           name=f"mint_cv.py [{ds}/{pred}]")
        run([PY, "src/evaluation/pplm_cv.py",
            "--dataset", ds, "--predictor", pred, "--n-gcv", str(N_GCV)],
           produces=[_GCV_DIR / f"PPLM_{pred}_{ds}_detailed_results.pkl"],
           name=f"pplm_cv.py [{ds}/{pred}]")
    run([PY, "src/evaluation/swing_gcv.py", "--dataset", ds],
       produces=[_GCV_DIR / f"SWING_{ds}_no_test_pretrain_detailed_results.pkl"],
       name=f"swing_gcv.py [{ds}, blind-test]")
    run([PY, "src/evaluation/swing_gcv.py", "--dataset", ds, "--test-pretrain"],
       produces=[_GCV_DIR / f"SWING_{ds}_test_pretrain_detailed_results.pkl"],
       name=f"swing_gcv.py [{ds}, test-pretrain]")
    run([PY, "src/evaluation/saambe3d_cv.py", "--dataset", ds, "--outdir", str(_GCV_DIR)],
       produces=[_GCV_DIR / f"{ds}_SAAMBE-3D_preds.npy"], name=f"saambe3d_cv.py [{ds}]")
    for variant, stem in ((0, "MutPPI"), (1, "MutPPIPlus")):
        run([PY, "src/evaluation/mutppi_cv.py",
            "--dataset", ds, "--model", str(variant), "--device", DEVICE, "--outdir", str(_GCV_DIR)],
           produces=[_GCV_DIR / f"{ds}_{stem}_preds.npy"], name=f"mutppi_cv.py [{ds}, {stem}]")

# %% [markdown]
# ### Step 4b -- MutPred2 (optional, off-machine)
#
# MutPred2 has no trainable model here; it is run externally. Off by default
# (`RUN_MUTPRED2`). When enabled, this exports ONE query FASTA -- the union of
# all five canonical datasets, including the blind-test target -- rather than
# a separate FASTA per dataset. MutPred2 scores a (protein, mutation) query
# independently of whatever else shares its FASTA batch, and
# `import_mutpred2_gcv_scores.py` / `import_mutpred2_varchamp_scores.py` both
# key strictly on (interactor, mutation), so one run's output CSV feeds every
# dataset's import with no duplicate queries. Then expects
# `import_mutpred2_gcv_scores.py` to have been run against the resulting
# output CSV before Step 5's figures include it.

# %%
_MP2_INPUT_DIR = DATASETS_DIR / "mutpred2_inputs"
_MP2_UNION_FASTA = _MP2_INPUT_DIR / "all_mutpred2_input.fasta"

if RUN_MUTPRED2:
    run([PY, "src/analysis/export_mutpred2_inputs.py", "--dataset", "all"],
       produces=[_MP2_UNION_FASTA], name="export_mutpred2_inputs.py [all]")
    print(f"  Run MutPred2 off-machine on {_MP2_UNION_FASTA}, then:")
    for ds in _GCV_DATASETS:
        if ds == _VARCHAMP_DATASET:
            continue  # blind-test target only, imported in Step 6
        print(f"    conda run -n ppi python src/analysis/import_mutpred2_gcv_scores.py "
              f"--dataset {ds} --csv <output.csv>")
else:
    print("[skip] MutPred2 GCV baseline (RUN_MUTPRED2=False); "
          "figures render without its curve.")

# %% [markdown]
# ## Step 5 -- Cross-validation figures (Fig 3, S3, S4, S1)

# %%
try:
    run([PY, "src/analysis/run_roc_comparison.py"], name="run_roc_comparison.py")
except RuntimeError as exc:
    print(f"[skip] run_roc_comparison.py: {exc}")

# The ablation figure (S4) omits the "Prior Best" bar by default. That bar is
# the previously published model rather than an ablation of this architecture,
# and its checkpoint ships in neither the repository nor the Zenodo deposit:
#
#   RECOMB model (bioRxiv v2): MutPred-PPI v1.0
#   https://github.com/rosstewart/MutPred-PPI/releases/tag/v1.0.0
#
# Add "--include-prior-best" below to draw it, once that release is unpacked
# into weights/v1_0/.
try:
    run([PY, "src/analysis/run_roc_ablation.py"], name="run_roc_ablation.py")
except RuntimeError as exc:
    print(f"[skip] run_roc_ablation.py: {exc}")

try:
    run([PY, "src/analysis/biclass_sf_gcv.py"], name="biclass_sf_gcv.py")
except RuntimeError as exc:
    print(f"[skip] biclass_sf_gcv.py: {exc}")

_ROC_DIR = _GCV_DIR / "roc_plots_with_variance"
show(_ROC_DIR / "roc_sahni_fragoza_with_variance.png", "Fig 3")
show(_ROC_DIR / "roc_sahni_with_variance.png", "S2")
show(_ROC_DIR / "ablation_bar_sahni_fragoza_with_variance.png", "S4")
show(_RESULTS_DIR / "biclass_gcv" / "roc_sahni_fragoza_biclass_with_variance.png", "S1")

# %% [markdown]
# ## Step 6 -- VarChAMP blind test (Fig 4, S3)
#
# Train on `sahni_fragoza_mapped090826`, predict on all of
# `varchamp_all_mapped090826` -- see `run_varchamp_blind_test.py`'s module
# docstring for why this replaced the retired `sfvcfp_rows.csv.gz` pipeline.
# **Requires unpublished VarChAMP data**; skips cleanly when absent.

# %%
# Gate on the canonical VarChAMP table itself, not the now-archived
# data_caches/training_data_internal.csv (moved to archive/pre_090826/ on
# 2026-09-10 -- it was never actually a required input; see the correction in
# the Zenodo deposit). The unpublished-data concern moved WITH the data:
# varchamp_all_mapped090826_rows.csv.gz carries the same unpublished VarChAMP
# measurements, and is what every step below actually reads.
_VARCHAMP_ROWS = _MAPPED / f'{dataset_name("varchamp_all")}_rows.csv.gz'
_VARCHAMP_AVAILABLE = _VARCHAMP_ROWS.exists()

if not _VARCHAMP_AVAILABLE:
    print(f"[skip] Step 6: {_VARCHAMP_ROWS} is absent -- Fig 4 and S2 are not "
          "independently reproducible without unpublished VarChAMP data.")
else:
    _BLIND_DIR = _RESULTS_DIR / "varchamp_seqcnf_newvar_eval"
    _blind_methods = [
        ("mutpredppi", {}), ("esignet", {}),
        ("mint", {"--predictor": "seq_diff"}), ("mint", {"--predictor": "site_diff"}),
        ("pplm", {"--predictor": "seq_diff"}), ("pplm", {"--predictor": "site_diff"}),
        ("swing", {}), ("saambe3d", {}), ("mutppi", {}), ("mutppiplus", {}),
    ]
    for method, extra in _blind_methods:
        cmd = [PY, "src/evaluation/run_varchamp_blind_test.py", "--method", method,
              "--device", DEVICE]
        for k, v in extra.items():
            cmd += [k, v]
        tag = "_" + extra.get("--predictor", "") if extra else ""
        try:
            run(cmd, name=f"run_varchamp_blind_test.py [{method}{tag}]")
        except RuntimeError as exc:
            print(f"[skip] {method}{tag}: {exc}")

    if RUN_MUTPRED2:
        print(f"  MutPred2 union FASTA already exported in Step 4b "
              f"({_MP2_UNION_FASTA}) -- it includes the blind-test target. "
              f"Run it off-machine, then:\n"
              f"    conda run -n ppi python src/analysis/import_mutpred2_varchamp_scores.py --csv <output.csv>")

    try:
        run([PY, "src/analysis/blind_test_figures.py"], name="blind_test_figures.py")
    except RuntimeError as exc:
        print(f"[skip] blind_test_figures.py: {exc}")

    show(_BLIND_DIR / "roc_plots" / "roc_varchamp_blind_test.png", "Fig 4")
    show(_BLIND_DIR / "roc_plots" / "roc_varchamp_blind_test_training_comparison.png", "S3")

# %% [markdown]
# ## Step 7 -- Final model and variant-repository inference
#
# The published tier trains one model on every labelled pair, with no fold
# split, and writes to `results/variant_dbs_all_data/`.
# `run_variant_db_inference.py::assert_all_data_model` refuses to run with
# anything else, so there is only ever one published variant-DB results tree.
#
# **Without the unpublished VarChAMP measurements that model cannot be trained.**
# Rather than skip the rest of the pipeline, the notebook falls back to the
# Sahni+Fragoza model shipped in the Zenodo weights bundle. That is a
# DEMONSTRATION: it lets you run variant-repository inference end to end and see
# what it produces, but its scores are not the paper's. Everything it writes goes
# to `results/variant_dbs_sahni_fragoza/` and every figure it draws is stamped,
# so the two tiers cannot be confused.

# %%
_DEMO_TIER = not _VARCHAMP_AVAILABLE
_VDB_DIR = _RESULTS_DIR / ("variant_dbs_all_data" if _VARCHAMP_AVAILABLE
                           else "variant_dbs_sahni_fragoza")
_VDB_STAB_DIR = _RESULTS_DIR / "variant_dbs_stability"
_TIER_ARGS = [] if _VARCHAMP_AVAILABLE else ["--model-tier", "sahni_fragoza"]

if _DEMO_TIER:
    _SF_CKPT = WEIGHTS_DIR / "sahni_fragoza" / "MutPred-PPI.pt"
    if not _SF_CKPT.exists():
        print(f"[skip] Steps 7-9: neither the unpublished VarChAMP data nor the "
              f"Sahni+Fragoza demonstration model ({_SF_CKPT}) is present. "
              f"The latter ships in the Zenodo weights bundle; see docs/DATA.md.")
    else:
        print("=" * 72)
        print("DEMONSTRATION TIER: VarChAMP data absent, using the Sahni+Fragoza")
        print("model. Results go to results/variant_dbs_sahni_fragoza/ and are")
        print("NOT the published numbers. See the 'What you can reproduce' table")
        print("in README.md.")
        print("=" * 72)

if _VARCHAMP_AVAILABLE:
    _ALL_DATA_CKPT_RAW = (WEIGHTS_DIR /
        f'MutPred-PPI_{dataset_name("sahni_fragoza_varchamp_all")}_megascale_all_all.pt')
    _ALL_DATA_CKPT = WEIGHTS_DIR / "MutPred-PPI.pt"  # the blessed name run_variant_db_inference.py and
                                                       # the public inference pipeline actually look for
    run([PY, "src/training/train_final_model.py",
        "--dataset", dataset_name("sahni_fragoza_varchamp_all"),
        "--ablation", "megascale_all", "--save-models-dir", str(WEIGHTS_DIR),
        "--device", DEVICE, "--no-cv"],
       produces=[_ALL_DATA_CKPT_RAW], name="train_final_model.py (all-data)")

    # Promotion step: train_final_model.py's own naming convention is dataset-qualified
    # (needed so GCV/blind-test/all-data checkpoints never collide on disk); nothing else
    # renames its output to the fixed name every consumer actually resolves against.
    # Without this, a fresh retrain silently has no effect on inference.
    if not FORCE and _ALL_DATA_CKPT.exists():
        print(f"[cached]  promote to MutPred-PPI.pt  (already present)")
    else:
        import shutil as _shutil
        _shutil.copy2(_ALL_DATA_CKPT_RAW, _ALL_DATA_CKPT)
        print(f"[run]     promoted {_ALL_DATA_CKPT_RAW.name} -> {_ALL_DATA_CKPT}")

# %%
# Inference itself runs in BOTH tiers -- only the model and the output tree
# differ. Stability (ddG) is tier-independent: run_stability_inference.py loads
# the MegaScale-pretrained model, which never saw VarChAMP.
if _VARCHAMP_AVAILABLE or (WEIGHTS_DIR / "sahni_fragoza" / "MutPred-PPI.pt").exists():
    for db in ("clinvar", "gnomad", "cosmic", "hgmd", "neurodev", "asd"):
        rows_path = DATASETS_DIR / "variant_dbs" / f"{db}_rows.csv.gz"
        if not rows_path.exists():
            print(f"[skip] {db}: {rows_path} not built (licensed data absent?)")
            continue
        cmd = [PY, "src/variant_db_inference/run_variant_db_inference.py",
              "--dataset", db, "--device", DEVICE,
              "--out", str(_VDB_DIR / f"{db}_mutpred_ppi_predictions.tsv")] + _TIER_ARGS
        if QUICK:
            cmd += ["--rows", str(subsample_rows(db, DB_SUBSAMPLE))]
        try:
            run(cmd, produces=[_VDB_DIR / f"{db}_mutpred_ppi_predictions.tsv"],
               name=f"run_variant_db_inference.py [{db}]")
            run([PY, "src/variant_db_inference/run_stability_inference.py",
                "--dataset", db, "--device", DEVICE, "--out-dir", str(_VDB_STAB_DIR)],
               produces=[_VDB_STAB_DIR / f"{db}_stability_predictions.tsv"],
               name=f"run_stability_inference.py [{db}]")
        except RuntimeError as exc:
            print(f"[skip] {db}: {exc}")

# %% [markdown]
# ## Step 8 -- Classification and bootstrap caches
#
# Runs in whichever tier Step 7 used, reading and writing `_VDB_DIR`.

# %%
# Gate on the predictions actually existing rather than on VarChAMP: in the
# demonstration tier they are there, just from the Sahni+Fragoza model.
_VDB_READY = any((_VDB_DIR / f"{db}_mutpred_ppi_predictions.tsv").exists()
                 for db in ("clinvar", "gnomad", "cosmic", "hgmd", "neurodev", "asd"))
_DEMO_ARGS = ["--demo-tier"] if _DEMO_TIER else []

if _VDB_READY:
    run([PY, "src/analysis/classify_variant_dbs.py", "--output-dir", str(_VDB_DIR),
        "--pred-dir", str(_VDB_DIR)],
       name="classify_variant_dbs.py")
    if not _DEMO_TIER:
        # The deposited master CSV is a published artifact; it is only built from
        # the all-data tier.
        run([PY, "src/analysis/make_master_variant_db_csv.py"],
           produces=[_RESULTS_DIR / "master_variant_db_predictions.csv.gz"],
           name="make_master_variant_db_csv.py")
    run([PY, "src/analysis/variant_db_charts.py",
        "--data-dir", str(_VDB_DIR), "--edgotype-bootstrap", "--controlled-bootstrap",
        "--k3-only", "--n-bootstrap", str(N_BOOTSTRAP)] + _DEMO_ARGS,
       produces=[_VDB_DIR / "all_bootstrap_results.pkl"], name="variant_db_charts.py [bootstrap]")
else:
    print("[skip] Step 8: needs Step 7's variant-DB predictions.")

# %% [markdown]
# ## Step 9 -- Variant-repository figures and tables (Fig 5, S6, S8, ...)

# %%
if _VDB_READY:
    run([PY, "src/analysis/variant_db_charts.py", "--data-dir", str(_VDB_DIR)] + _DEMO_ARGS,
       name="variant_db_charts.py [Fig 5]")
    # The k=3 figure (S7) is written by the --controlled-bootstrap --k3-only run
    # in Step 8; there is no separate pass. `--controlled-k 3` is not an argument
    # variant_db_charts.py accepts, so this call aborted the notebook.
    show(_VDB_DIR / "enrichment_bootstrap_sufficient_partners.png", "Fig 5")
    show(_VDB_DIR / "enrichment_bootstrap_sufficient_partners_k3.png", "S7")

    run([PY, "src/analysis/threshold_sensitivity.py", "--n-bootstrap", str(N_BOOTSTRAP),
        "--data-dir", str(_VDB_DIR)] + _DEMO_ARGS,
       name="threshold_sensitivity.py")

    # Optional presentation figure: quasi-null against edgetic enrichment on one
    # pair of axes, read from the bootstrap cache the Fig 5 step already wrote.
    # Not a manuscript figure, so it is off unless PRESENTATION_FIGURES is set.
    if PRESENTATION_FIGURES:
        run([PY, "src/analysis/enrichment_scatter.py",
            "--cache", str(_VDB_DIR / "all_bootstrap_results.pkl"),
            "--out", str(_VDB_DIR / "enrichment_scatter.png")] + _DEMO_ARGS,
           name="enrichment_scatter.py")
        show(_VDB_DIR / "enrichment_scatter.png", "enrichment scatter (slides)")
    show(_RESULTS_DIR / "robustness" / "threshold_sensitivity.png", "S8")

    run([PY, "src/analysis/protein_class_enrichment.py"], name="protein_class_enrichment.py")
    show(_RESULTS_DIR / "protein_class" / "pathogenic_by_class.png", "S9")

    # One figure, two panels. (A) one point per variant sample:
    # stability-disruption enrichment (x) against PPI-disruption enrichment (y),
    # both relative to gnomAD and both using the same statistic as Fig 5, with
    # the binned gnomAD/COSMIC/oncogene/TSG categories drawn as progressions.
    # (B) the per-variant density behind twelve of those samples.
    run([PY, "src/analysis/stability_interaction_scatter.py", "--panels", "full",
        "--data-dir", str(_VDB_DIR)] + _DEMO_ARGS,
       name="stability_interaction_scatter.py")
    show(_RESULTS_DIR / "stability_interaction" / "stability_interaction_scatter.png",
         "S10")

    try:
        run([PY, "src/analysis/combined_robustness_figure.py"], name="combined_robustness_figure.py")
        show(_RESULTS_DIR / "robustness" / "combined_robustness_by_class.png", "S5")
    except RuntimeError as exc:
        print(f"[skip] combined_robustness_figure.py: {exc}")

    run([PY, "src/analysis/cosmic_onco_tsg_stat_test.py"], name="cosmic_onco_tsg_stat_test.py")
else:
    print("[skip] Step 9 variant-DB figures: needs Step 7/8's predictions.")

if _VARCHAMP_AVAILABLE:
    run([PY, "src/analysis/generate_training_table.py"],
       produces=[REPO / "figures" / "training_data_table.tex"], name="generate_training_table.py [Table 1]")
else:
    print("[skip] Table 1: generate_training_table.py needs the unpublished "
          f"VarChAMP measurements in {_VARCHAMP_ROWS.name}.")

run([PY, "src/analysis/extract_variant_db_stats.py"],
   produces=[REPO / "figures" / "variant_db_stats_table.tex"], name="extract_variant_db_stats.py [Table S1]")

for tex_name, caption in (("training_data_table.tex", "Table 1"),
                          ("variant_db_stats_table.tex", "Table S1")):
    p = REPO / "figures" / tex_name
    if p.exists():
        print(f"\n--- {caption} ({tex_name}) --- PASTE INTO THE MANUSCRIPT BY HAND (no \\input{{}}) ---")
        print(p.read_text())

# %% [markdown]
# ## Step 9b -- Reconstruction tables
#
# Flattens `results/gcv/*_detailed_results.pkl` into per-figure CSVs, so every
# ROC and PR curve can be recomputed with no training, no GPU and no access to
# the splits. These are a convenience, not a deposit: the pickles they are built
# from are themselves deposited and hold the same preds and labels.

# %%
run([PY, "src/analysis/export_reconstruction_tables.py", "--figure", "all"],
   produces=[DATASETS_DIR / "reconstruction_tables" / "README.md"],
   name="export_reconstruction_tables.py")

# %% [markdown]
# ## Step 10 -- Manifest and figures/
#
# Every manuscript figure and table: expected path, whether it exists, and its
# age. This step also (re)builds the `figures/` symlinks from the same manifest,
# so a producer that changes its output path cannot leave a dangling link behind.
# Each link is named after its target, so there is exactly one name per figure;
# the label -> file mapping is in docs/REPRODUCING_ANALYSES.md.

# %%
import datetime

_MANIFEST = [
    ("Fig 3",  _ROC_DIR / "roc_sahni_fragoza_with_variance.png"),
    ("S2",     _ROC_DIR / "roc_sahni_with_variance.png"),
    ("S4",     _ROC_DIR / "ablation_bar_sahni_fragoza_with_variance.png"),
    ("S6",     _ROC_DIR / "roc_sahni_fragoza_varchamp_all_with_variance.png"),
    ("S1", _RESULTS_DIR / "biclass_gcv" / "roc_sahni_fragoza_biclass_with_variance.png"),
    ("Fig 4",  _RESULTS_DIR / "varchamp_seqcnf_newvar_eval" / "roc_plots" / "roc_varchamp_blind_test.png"),
    ("S3",     _RESULTS_DIR / "varchamp_seqcnf_newvar_eval" / "roc_plots" / "roc_varchamp_blind_test_training_comparison.png"),
    ("Fig 5",  _VDB_DIR / "enrichment_bootstrap_sufficient_partners.png"),
    ("S7",     _VDB_DIR / "enrichment_bootstrap_sufficient_partners_k3.png"),
    ("S8",     _RESULTS_DIR / "robustness" / "threshold_sensitivity.png"),
    ("S9", _RESULTS_DIR / "protein_class" / "pathogenic_by_class.png"),
    ("S10", _RESULTS_DIR / "stability_interaction" / "stability_interaction_scatter.png"),
    ("S5", _RESULTS_DIR / "robustness" / "combined_robustness_by_class.png"),
    ("Table 1", REPO / "figures" / "training_data_table.tex"),
    ("Table S1", REPO / "figures" / "variant_db_stats_table.tex"),
]

# Figures for talks rather than the paper. They are linked into figures/ and
# pruned alongside the rest, but carry no manuscript number, so the numbering
# check that reads main_*.tex/supplement_*.tex skips them.
_PRESENTATION_MANIFEST = [
    ("enrichment scatter (slides)", _VDB_DIR / "enrichment_scatter.png"),
]

print(f"{'label':<14} {'exists':<7} {'age':<12} path")
for label, path in _MANIFEST + (_PRESENTATION_MANIFEST if PRESENTATION_FIGURES else []):
    exists = path.exists()
    age = (datetime.datetime.now() - datetime.datetime.fromtimestamp(path.stat().st_mtime)
          ) if exists else None
    age_str = f"{age.days}d" if age else "-"
    print(f"{label:<14} {'yes' if exists else 'NO':<7} {age_str:<12} {path}")

# Rebuild figures/ from the manifest. Only PNGs are linked: the .tex tables are
# written directly into figures/ by their producers.
_FIG_DIR = REPO / "figures"
_FIG_DIR.mkdir(exist_ok=True)
_wanted = {}
for label, path in _MANIFEST + _PRESENTATION_MANIFEST:
    if path.suffix != ".png" or not path.exists():
        continue
    link = _FIG_DIR / path.name
    _wanted[link.name] = path
    rel = os.path.relpath(path, _FIG_DIR)
    if link.is_symlink() and os.readlink(link) == rel:
        continue
    if link.is_symlink() or link.exists():
        link.unlink()
    link.symlink_to(rel)
    print(f"[link]    figures/{link.name} -> {rel}")

# Drop links the manifest no longer names, and any left dangling.
for link in _FIG_DIR.glob("*.png"):
    if link.name not in _wanted or not link.resolve().exists():
        link.unlink()
        print(f"[unlink]  figures/{link.name} (no longer produced)")

print(f"\nfigures/ holds {len(_wanted)} figures + "
      f"{len(list(_FIG_DIR.glob('*.tex')))} tables")

print("\nDrawn by hand, not regenerated by anything in this repo:")
print("  Fig 1 (MutPred-PPI_pipeline.png), Fig 2 (MutPred-PPI_architecture.png), "
      "the CDC42 example panel (CDC42_WASP_Y64.png)")
