# %% [markdown]
# # Reproduce every MutPred-PPI figure and table, from scratch
#
# Runner notebook for the MutPred-PPI publication repo. Given the Zenodo
# deposit (`datasets/`, `weights/`) it regenerates, in order: stability
# pretraining -> the canonical data layer and contact-graph store ->
# embeddings for every method -> group cross-validation (GCV) -> the
# VarChAMP blind test -> the final all-data model -> variant-repository
# inference -> every manuscript figure and table.
#
# **Caching.** Every step checks whether its output already exists before
# doing anything, so a second run of the whole notebook with `FORCE=False`
# finishes in well under a minute. Embedding/GCV/inference scripts also
# resume by content key internally, so re-running one is cheap even after a
# partial failure.
#
# **QUICK mode.** `QUICK=True` runs 1 GCV seed (not 30), subsamples the
# variant databases, and shrinks the enrichment bootstraps -- the whole
# pipeline finishes in hours instead of the days a full run takes, for
# smoke-testing the chain. **Quick-mode output never touches the canonical
# `results/` tree that `figures/*.png` symlink into** -- it is redirected to
# a sandbox via `MUTPRED_PPI_RESULTS_DIR` (see `src/paths.py`).
#
# **Only `datasets/training_eval/` data is ever read.** Every dataset name is
# one of the five `*_mapped090826` configs in `utils.gcv_common.DATASET_CONFIGS`;
# `utils.legacy_guard` raises rather than silently accepting anything from the
# retired pre-090826 pipeline (`.mat`/`.pos`/`.neg`/`.labels`/`.vt_ids` files,
# `all_vt_ids_and_labels.txt`, `sfvcfp_rows.csv.gz`, `training_data_internal.csv`,
# ...). See `docs/FIGURE_INVENTORY.md` for the full inventory this notebook
# was built to satisfy, and `docs/REPRODUCING_ANALYSES.md` for the underlying
# per-script commands this notebook wraps.
#
# **Data is not final.** AF3 structures were still generating when this
# notebook was written (2026-09-10); run it once whatever exists to
# smoke-test the chain, and again in full once the AF3 run completes.
#
# **Not reproducible here, by design:**
# Fig 4/S2 and Table 1 need unpublished VarChAMP data, present only in
# `datasets/training_eval/varchamp_all_mapped090826_rows.csv.gz`; those steps
# detect its absence and skip with a clear message rather than failing. Figs
# 1 and 2 (pipeline, architecture) and the CDC42 example panel are drawn by
# hand and are not regenerated by anything in this repo.

# %% Configuration
import os
from pathlib import Path

QUICK = True          # 1 GCV seed, subsampled variant DBs, small bootstraps
FORCE = False          # recompute even when a cached output already exists
DEVICE = "cuda:0"
RUN_PRETRAIN = False    # Step 1; off by default, uses the deposited checkpoint
RUN_MUTPRED2 = False    # Step 4b/6; MutPred2 runs off-machine, off by default
DRY_RUN = False         # print commands instead of executing them

REPO = Path(__file__).resolve().parent.parent if "__file__" in dir() else Path.cwd().parent
os.chdir(REPO)

N_GCV = 1 if QUICK else 30
N_BOOTSTRAP = 1_000 if QUICK else 100_000
DB_SUBSAMPLE = 20_000 if QUICK else None   # rows per variant DB; None = all

# Every results/<subdir> constant in src/paths.py derives from this one env
# var (see src/paths.py's MUTPRED_PPI_RESULTS_DIR docstring), so setting it
# before any src/ import redirects the *entire* results/ tree at once.
_RESULTS_DIR = REPO / "results_quick" if QUICK else REPO / "results"
os.environ["MUTPRED_PPI_RESULTS_DIR"] = str(_RESULTS_DIR)

print(f"QUICK={QUICK}  FORCE={FORCE}  DEVICE={DEVICE}")
print(f"Results root: {_RESULTS_DIR}"
      + ("  (sandbox -- canonical results/ untouched)" if QUICK else "  (canonical)"))

# %% Shared helpers
import subprocess
import sys
import time

import pandas as pd
from IPython.display import Image, display

sys.path.insert(0, str(REPO / "src"))
from paths import DATA_ROOT, DATASETS_DIR, REPO_ROOT, TRAINING_EVAL_DIR, WEIGHTS_DIR, describe  # noqa: E402
from utils.legacy_guard import LegacyInputError, reject_legacy  # noqa: E402

_ENV = {**os.environ, "MPLBACKEND": "Agg", "OPENBLAS_NUM_THREADS": "1"}


def run(cmd: list, *, produces: list | None = None, name: str | None = None,
       cwd: Path | None = None) -> None:
    """Run a command, skipping it if every `produces` path already exists.

    This is the whole caching layer: a second notebook run with
    `FORCE=False` finds every `produces` path present and does nothing.
    """
    label = name or Path(str(cmd[2]) if len(cmd) > 2 else cmd[0]).name
    produces = [Path(p) for p in (produces or [])]
    if produces and not FORCE and all(p.exists() for p in produces):
        print(f"[cached]  {label}  ({len(produces)} output(s) present)")
        return
    print(f"[run]     {label}")
    print(f"          {' '.join(str(c) for c in cmd)}")
    if DRY_RUN:
        return
    t0 = time.time()
    result = subprocess.run(cmd, cwd=str(cwd or REPO), env=_ENV,
                            capture_output=True, text=True)
    dt = time.time() - t0
    tail = "\n".join(result.stdout.splitlines()[-20:])
    print(tail)
    if result.returncode != 0:
        print(result.stderr[-4000:])
        raise RuntimeError(f"{label} failed (exit {result.returncode}) after {dt:.0f}s")
    print(f"          done in {dt:.0f}s")


def show(path, caption: str = "") -> None:
    """Display a figure inline; warn (don't raise) if it isn't there yet."""
    path = Path(path)
    if not path.exists():
        print(f"[missing] {caption or path.name}: {path}")
        return
    print(f"{caption or path.name}  ->  {path}")
    display(Image(filename=str(path)))


def assert_fresh(*paths) -> None:
    """Refuse pre-090826 artifacts -- thin wrapper over utils.legacy_guard."""
    reject_legacy(*paths)


def subsample_rows(db: str, n: int, seed: int = 0) -> Path:
    """A seeded subsample of a variant-DB row table, for QUICK-mode --rows."""
    src = DATASETS_DIR / "variant_dbs" / f"{db}_rows.csv.gz"
    out_dir = _RESULTS_DIR / "_quick_subsamples"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{db}_rows_n{n}.csv.gz"
    if out.exists() and not FORCE:
        return out
    df = pd.read_csv(src)
    df.sample(n=min(n, len(df)), random_state=seed).to_csv(out, index=False)
    return out


PY = sys.executable

# %% [markdown]
# ## Step 0 -- Preflight
#
# Installs the package, prints every resolved path (`src/paths.py::describe()`),
# and checks the tools cross-validation needs.

# %%
run([PY, "-m", "pip", "install", "-e", "."], name="pip install -e .")
print(describe())

# %%
import shutil

if shutil.which("cd-hit") is None:
    print("[note] cd-hit not on PATH -- only needed to rebuild splits from "
          "scratch; datasets/cv_reference/ ships the published splits, so "
          "GCV does not need it for a normal run.")
else:
    print(f"cd-hit: {shutil.which('cd-hit')}")

import torch
print(f"CUDA available: {torch.cuda.is_available()}  "
      f"device count: {torch.cuda.device_count() if torch.cuda.is_available() else 0}")

# %% [markdown]
# ## Step 1 -- Stability pretraining (optional)
#
# Off by default: the deposited `weights/MutPred-PPI_stability_pretrain.pt`
# is what every fine-tuned model starts from. Set `RUN_PRETRAIN = True` to
# regenerate it from raw sources -- download
# `Tsuboyama2023_Dataset2_Dataset3_20230416.csv` and `AlphaFold_model_PDBs.zip`
# from <https://zenodo.org/records/7992926> first.

# %%
_STABILITY_CKPT = WEIGHTS_DIR / "MutPred-PPI_stability_pretrain.pt"

if not RUN_PRETRAIN:
    if _STABILITY_CKPT.exists():
        print(f"[cached]  using deposited checkpoint: {_STABILITY_CKPT}")
    else:
        print(f"[missing] {_STABILITY_CKPT} -- set RUN_PRETRAIN=True, or "
              f"deposit weights/MutPred-PPI_stability_pretrain.pt")
else:
    _MEGASCALE_CSV = DATA_ROOT / "Tsuboyama2023_Dataset2_Dataset3_20230416.csv"
    _MEGASCALE_PDBS = DATA_ROOT / "AlphaFold_model_PDBs"
    _MEGASCALE_OUT = REPO / "megascale_preprocessed"
    for p in (_MEGASCALE_CSV, _MEGASCALE_PDBS):
        if not p.exists():
            raise FileNotFoundError(
                f"{p} not found. Download from https://zenodo.org/records/7992926 "
                f"(Tsuboyama2023_Dataset2_Dataset3_20230416.csv, AlphaFold_model_PDBs.zip) "
                f"and place under {DATA_ROOT}.")
    run([PY, "src/training/preprocess_stability_data.py",
        "--csv", str(_MEGASCALE_CSV), "--pdb-dir", str(_MEGASCALE_PDBS),
        "--splits", str(DATASETS_DIR / "mega_splits.pkl"),
        "--outdir", str(_MEGASCALE_OUT), "--device", DEVICE, "--n-jobs", "16"],
       produces=[_MEGASCALE_OUT / "preprocessed.pkl",
                 _MEGASCALE_OUT / "mutation_diff_scaler.pkl"],
       name="preprocess_stability_data.py")
    run([PY, "src/training/pretrain_stability.py",
        "--data", str(_MEGASCALE_OUT / "preprocessed.pkl"),
        "--scaler", str(_MEGASCALE_OUT / "mutation_diff_scaler.pkl"),
        "--outmodel", str(_STABILITY_CKPT), "--device", DEVICE],
       produces=[_STABILITY_CKPT], name="pretrain_stability.py")

# %% [markdown]
# ## Step 2 -- Canonical data layer and caches
#
# Structures -> contact graphs -> canonical row tables -> CV reference
# splits -> the small annotation caches every figure script reads. Every
# output here is content-addressed or dataset-scoped, so re-running with
# `FORCE=False` is a no-op once built.

# %%
_AF3_CANON = DATASETS_DIR / "af3_structures_canonical"
_AF3_DB_CANON = DATASETS_DIR / "af3_structures_variant_dbs_canonical"
_MAPPED = TRAINING_EVAL_DIR

run([PY, "src/data_processing/canonicalize_structures.py",
    "--structures", str(DATASETS_DIR / "af3_structures"), "--out", str(_AF3_CANON)],
   produces=[_AF3_CANON / "manifest.csv"], name="canonicalize_structures.py (train/eval)")
run([PY, "src/data_processing/canonicalize_structures.py",
    "--structures", str(DATASETS_DIR / "af3_structures_variant_dbs"), "--out", str(_AF3_DB_CANON)],
   produces=[_AF3_DB_CANON / "manifest.csv"], name="canonicalize_structures.py (variant DBs)")

run([PY, "src/data_processing/rebuild_graphs_from_structures.py",
    "--structures", str(_AF3_CANON), "--out", str(_MAPPED / "contact_graphs.h5")],
   produces=[_MAPPED / "contact_graphs.h5"], name="rebuild_graphs_from_structures.py (train/eval)")
run([PY, "src/data_processing/rebuild_graphs_from_structures.py",
    "--structures", str(_AF3_DB_CANON),
    "--out", str(DATASETS_DIR / "variant_dbs" / "contact_graphs.h5")],
   produces=[DATASETS_DIR / "variant_dbs" / "contact_graphs.h5"],
   name="rebuild_graphs_from_structures.py (variant DBs)")

# The GCV row/split tables. Stage 2 of the data-preparation chain: reads the
# mapping CSVs in datasets/source_mapping/ (built by
# notebooks/map_ppi_datasets_090826.py) and writes datasets/training_eval/.
# Must run BEFORE prepare_af3_inputs.py, which derives its required-pair set
# from these tables. Moved here from repro_test/build_canonical_tables.py and
# renamed 2026-09-10 -- the old name was ambiguous with the mapping notebook,
# and it lived in a gitignored directory. See docs/DATA_PREPARATION.md.
run([PY, "src/data_processing/training_sets/prepare_gcv_tables.py",
    "--n-seeds", str(N_GCV)],
   produces=[_MAPPED / "sahni_fragoza_mapped090826_rows.csv.gz"],
   name="prepare_gcv_tables.py")

# Prepares AlphaFold3 inputs for every complex not already folded (required =
# union of all five canonical datasets, since the pooled
# sahni_fragoza_varchamp_all can drop a conflicting row that is still valid,
# unconflicted data in a smaller dataset). Exits cleanly when nothing is
# missing. Does not gate anything below: rows without a structure are excluded
# by the shared per-class AUC wherever they turn up. Folding the emitted JSONs
# is a manual, off-box step -- see docs/DATA_PREPARATION.md.
run([PY, "src/data_processing/prepare_af3_inputs.py"],
   name="prepare_af3_inputs.py")
run([PY, "src/variant_db_inference/build_variant_db_tables.py", "--db", "all"],
   produces=[DATASETS_DIR / "variant_dbs" / "clinvar_rows.csv.gz"],
   name="build_variant_db_tables.py")
run([PY, "src/analysis/export_cv_reference.py", "--dataset", "all", "--n-seeds", str(N_GCV)],
   produces=[DATASETS_DIR / "cv_reference" / "sahni_fragoza_train_rows.csv.gz"],
   name="export_cv_reference.py")

_ANNOT = DATASETS_DIR / "annotations"
run([PY, "src/analysis/build_plddt_cache.py",
    "--output", str(_ANNOT / "plddt_pair_cache.pkl"), "--force"],
   produces=[_ANNOT / "plddt_pair_cache.pkl"], name="build_plddt_cache.py")
run([PY, "src/analysis/build_confidence_cache.py",
    "--json-dir", str(DATA_ROOT), "--recursive",
    "--output", str(_ANNOT / "confidence_scores.pkl"), "--force"],
   produces=[_ANNOT / "confidence_scores.pkl"], name="build_confidence_cache.py")
run([PY, "src/analysis/build_ar_ad_gene_sets.py"],
   produces=[_ANNOT / "clingen_ar_ad_uniprot_sets.pkl"], name="build_ar_ad_gene_sets.py")
run([PY, "src/analysis/fetch_protein_class_annotations.py"],
   produces=[_RESULTS_DIR / "protein_class" / "protein_class_annotations.csv"],
   name="fetch_protein_class_annotations.py")

# %% [markdown]
# ## Step 3 -- Embeddings
#
# ProtT5 (MutPred-PPI), ESM-2 (eSIG-Net), MINT, PPLM -- one cache per dataset.
# QUICK mode covers `sahni_fragoza_mapped090826` only (Fig 3); full mode adds
# `sahni_only_mapped090826` (S1) and `sahni_fragoza_varchamp_all_mapped090826`
# (S7), plus `varchamp_all_mapped090826` for the blind test. SWING needs no
# precomputed cache -- Doc2Vec is fit per run.

# %%
_GCV_DATASETS = (["sahni_fragoza_mapped090826", "varchamp_all_mapped090826"] if QUICK
                 else ["sahni_only_mapped090826", "sahni_fragoza_mapped090826",
                       "sahni_fragoza_varchamp_all_mapped090826", "varchamp_all_mapped090826"])

for ds in _GCV_DATASETS:
    run([PY, "src/data_processing/precompute_prott5_datasets.py",
        "--dataset", ds, "--device", DEVICE],
       produces=[_MAPPED / f"{ds}_prott5.pkl"], name=f"precompute_prott5_datasets.py [{ds}]")
    run([PY, "src/data_processing/precompute_esm2_datasets.py",
        "--dataset", ds, "--device", DEVICE],
       produces=[_MAPPED / f"{ds}_esm2.pkl"], name=f"precompute_esm2_datasets.py [{ds}]")
    run([PY, "src/evaluation/precompute_mint_embeddings.py",
        "--dataset", ds, "--device", DEVICE, "--compute-residue"],
       produces=[_MAPPED / f"{ds}_mint.pkl"], name=f"precompute_mint_embeddings.py [{ds}]")
    run([PY, "src/evaluation/precompute_pplm_embeddings.py",
        "--dataset", ds, "--device", DEVICE],
       produces=[_MAPPED / f"{ds}_pplm.pkl"], name=f"precompute_pplm_embeddings.py [{ds}]")

# %% [markdown]
# ## Step 4 -- Group cross-validation (Fig 3, S1, S7)
#
# One command per method. `--n-gcv {N_GCV}` throughout (30 in a full run, 1
# in QUICK mode). MutPred-PPI, eSIG-Net, MINT x2, PPLM x2, SWING x2 are
# retrained per dataset; SAAMBE-3D/MutPPI/MutPPI+ are pretrained (SKEMPI) and
# just scored.
#
# **Note (2026-09-10):** `roc_plots.py`/`utils/gcv_common.py` were under
# active parallel development while this notebook was written (a
# `StaleCacheError` guard that validates GCV pkl row counts against the
# canonical table, more thorough than what this notebook alone provides). If
# Step 5 raises `StaleCacheError`, that guard is doing its job -- rerun the
# affected GCV command for that dataset, not this notebook.

# %%
_GCV_DIR = _RESULTS_DIR / "gcv"


def gcv_stem(method: str, dataset: str, *, ablation: str = "") -> str:
    tag = f"_{ablation}" if ablation else ""
    return f"{method}_{dataset}{tag}"


for ds in _GCV_DATASETS:
    if ds == "varchamp_all_mapped090826":
        continue  # blind-test target only, not a GCV training set
    run([PY, "src/evaluation/mutpred_ppi_gcv.py",
        "--dataset", ds, "--device", DEVICE, "--n-gcv", str(N_GCV)],
       produces=[_GCV_DIR / f"{gcv_stem('MutPredPPI', ds, ablation='megascale_all')}_detailed_results.pkl"],
       name=f"mutpred_ppi_gcv.py [{ds}]")
    run([PY, "src/evaluation/esignet_cv.py",
        "--dataset", ds, "--device", DEVICE, "--n-gcv", str(N_GCV)],
       produces=[_GCV_DIR / f"ESigNet_{ds}_detailed_results.pkl"], name=f"esignet_cv.py [{ds}]")
    for pred in ("seq_diff", "site_diff"):
        run([PY, "src/evaluation/mint_cv.py",
            "--dataset", ds, "--predictor", pred, "--n-gcv", str(N_GCV)],
           produces=[_GCV_DIR / f"MINT_{pred}_{ds}_detailed_results.pkl"],
           name=f"mint_cv.py [{ds}/{pred}]")
        run([PY, "src/evaluation/pplm_cv.py",
            "--dataset", ds, "--predictor", pred, "--n-gcv", str(N_GCV)],
           produces=[_GCV_DIR / f"PPLM_{pred}_{ds}_detailed_results.pkl"],
           name=f"pplm_cv.py [{ds}/{pred}]")
    run([PY, "src/evaluation/swing_gcv.py", "--dataset", ds],
       produces=[_GCV_DIR / f"SWING_{ds}_no_test_pretrain_detailed_results.pkl"],
       name=f"swing_gcv.py [{ds}, blind-test]")
    run([PY, "src/evaluation/swing_gcv.py", "--dataset", ds, "--test-pretrain"],
       produces=[_GCV_DIR / f"SWING_{ds}_test_pretrain_detailed_results.pkl"],
       name=f"swing_gcv.py [{ds}, test-pretrain]")
    run([PY, "src/evaluation/saambe3d_cv.py", "--dataset", ds, "--outdir", str(_GCV_DIR)],
       produces=[_GCV_DIR / f"{ds}_SAAMBE-3D_preds.npy"], name=f"saambe3d_cv.py [{ds}]")
    for variant, stem in ((0, "MutPPI"), (1, "MutPPIPlus")):
        run([PY, "src/evaluation/mutppi_cv.py",
            "--dataset", ds, "--model", str(variant), "--device", DEVICE, "--outdir", str(_GCV_DIR)],
           produces=[_GCV_DIR / f"{ds}_{stem}_preds.npy"], name=f"mutppi_cv.py [{ds}, {stem}]")

# %% [markdown]
# ### Step 4b -- MutPred2 (optional, off-machine)
#
# MutPred2 has no trainable model here; it is run externally. Off by default
# (`RUN_MUTPRED2`). When enabled, this exports the query FASTA/substitution
# files, then expects `import_mutpred2_gcv_scores.py` to have been run
# against the resulting output CSV before Step 5's figures include it.

# %%
_MP2_INPUT_DIR = DATASETS_DIR / "mutpred2_inputs"

if RUN_MUTPRED2:
    for ds in _GCV_DATASETS:
        if ds == "varchamp_all_mapped090826":
            continue  # blind-test target only, handled in Step 6
        fasta = _MP2_INPUT_DIR / f"{ds}_mutpred2_input.fasta"
        run([PY, "src/analysis/export_mutpred2_inputs.py", "--dataset", ds],
           produces=[fasta], name=f"export_mutpred2_inputs.py [{ds}]")
        print(f"  Run MutPred2 off-machine on {fasta}, then:\n"
              f"    conda run -n ppi python src/analysis/import_mutpred2_gcv_scores.py "
              f"--dataset {ds} --csv <output.csv>")
else:
    print("[skip] MutPred2 GCV baseline (RUN_MUTPRED2=False); "
          "figures render without its curve.")

# %% [markdown]
# ## Step 5 -- Cross-validation figures (Fig 3, S1, S3, S-biclass)

# %%
try:
    run([PY, "src/analysis/run_roc_comparison.py"], name="run_roc_comparison.py")
except RuntimeError as exc:
    print(f"[skip] run_roc_comparison.py: {exc}")

try:
    run([PY, "src/analysis/run_roc_ablation.py"], name="run_roc_ablation.py")
except RuntimeError as exc:
    print(f"[skip] run_roc_ablation.py: {exc}")

try:
    run([PY, "src/analysis/biclass_sf_gcv.py"], name="biclass_sf_gcv.py")
except RuntimeError as exc:
    print(f"[skip] biclass_sf_gcv.py: {exc}")

_ROC_DIR = _GCV_DIR / "roc_plots_with_variance"
show(_ROC_DIR / "roc_sahni_fragoza_with_variance.png", "Fig 3")
show(_ROC_DIR / "roc_sahni_with_variance.png", "S1")
show(_ROC_DIR / "ablation_bar_sahni_fragoza_with_variance.png", "S3")
show(_RESULTS_DIR / "biclass_gcv" / "roc_sahni_fragoza_biclass_with_variance.png", "S-biclass")

# %% [markdown]
# ## Step 6 -- VarChAMP blind test (Fig 4, S2)
#
# Train on `sahni_fragoza_mapped090826`, predict on all of
# `varchamp_all_mapped090826` -- see `run_varchamp_blind_test.py`'s module
# docstring for why this replaced the retired `sfvcfp_rows.csv.gz` pipeline.
# **Requires unpublished VarChAMP data**; skips cleanly when absent.

# %%
# Gate on the canonical VarChAMP table itself, not the now-archived
# data_caches/training_data_internal.csv (moved to archive/pre_090826/ on
# 2026-09-10 -- it was never actually a required input; see the correction in
# the Zenodo deposit). The unpublished-data concern moved WITH the data:
# varchamp_all_mapped090826_rows.csv.gz carries the same unpublished VarChAMP
# measurements, and is what every step below actually reads.
_VARCHAMP_AVAILABLE = (_MAPPED / "varchamp_all_mapped090826_rows.csv.gz").exists()

if not _VARCHAMP_AVAILABLE:
    print("[skip] Step 6: datasets/training_eval/varchamp_all_mapped090826_rows.csv.gz "
          "is absent -- Fig 4 and S2 are not independently reproducible without "
          "unpublished VarChAMP data.")
else:
    _BLIND_DIR = _RESULTS_DIR / "varchamp_seqcnf_newvar_eval"
    _blind_methods = [
        ("mutpredppi", {}), ("esignet", {}),
        ("mint", {"--predictor": "seq_diff"}), ("mint", {"--predictor": "site_diff"}),
        ("pplm", {"--predictor": "seq_diff"}), ("pplm", {"--predictor": "site_diff"}),
        ("swing", {}), ("saambe3d", {}), ("mutppi", {}), ("mutppiplus", {}),
    ]
    for method, extra in _blind_methods:
        cmd = [PY, "src/evaluation/run_varchamp_blind_test.py", "--method", method,
              "--device", DEVICE]
        for k, v in extra.items():
            cmd += [k, v]
        tag = "_" + extra.get("--predictor", "") if extra else ""
        try:
            run(cmd, name=f"run_varchamp_blind_test.py [{method}{tag}]")
        except RuntimeError as exc:
            print(f"[skip] {method}{tag}: {exc}")

    if RUN_MUTPRED2:
        _mp2_va_fasta = _MP2_INPUT_DIR / "varchamp_all_mapped090826_mutpred2_input.fasta"
        run([PY, "src/analysis/export_mutpred2_inputs.py", "--dataset", "varchamp_all_mapped090826"],
           produces=[_mp2_va_fasta], name="export_mutpred2_inputs.py [varchamp_all_mapped090826]")
        print(f"  Run MutPred2 off-machine on {_mp2_va_fasta}, then:\n"
              f"    conda run -n ppi python src/analysis/import_mutpred2_varchamp_scores.py --csv <output.csv>")

    try:
        run([PY, "src/analysis/varchamp_blind_test.py"], name="varchamp_blind_test.py")
    except RuntimeError as exc:
        print(f"[skip] varchamp_blind_test.py: {exc}")

    show(_BLIND_DIR / "roc_plots" / "roc_varchamp_blind_test.png", "Fig 4")
    show(_BLIND_DIR / "roc_plots" / "roc_varchamp_blind_test_training_comparison.png", "S2")

# %% [markdown]
# ## Step 7 -- Final all-data model and variant-repository inference
#
# One model, `sahni_fragoza_varchamp_all_mapped090826`, no fold split.
# `run_variant_db_inference.py::assert_all_data_model` refuses to run with
# anything else (e.g. `weights/folds/`, the GCV fold ensemble) -- there must
# be only one variant-DB results tree (`results/variant_dbs_all_data/`).

# %%
if not _VARCHAMP_AVAILABLE:
    print("[skip] Step 7: final all-data model needs the same unpublished "
          "VarChAMP data as Step 6.")
else:
    _ALL_DATA_CKPT_RAW = WEIGHTS_DIR / "MutPred-PPI_sahni_fragoza_varchamp_all_mapped090826_megascale_all_all.pt"
    _ALL_DATA_CKPT = WEIGHTS_DIR / "MutPred-PPI.pt"  # the blessed name run_variant_db_inference.py and
                                                       # the public inference pipeline actually look for
    run([PY, "src/training/train_final_model.py",
        "--dataset", "sahni_fragoza_varchamp_all_mapped090826",
        "--ablation", "megascale_all", "--save-models-dir", str(WEIGHTS_DIR),
        "--device", DEVICE, "--no-cv"],
       produces=[_ALL_DATA_CKPT_RAW], name="train_final_model.py (all-data)")

    # Promotion step: train_final_model.py's own naming convention is dataset-qualified
    # (needed so GCV/blind-test/all-data checkpoints never collide on disk); nothing else
    # renames its output to the fixed name every consumer actually resolves against.
    # Without this, a fresh retrain silently has no effect on inference.
    if not FORCE and _ALL_DATA_CKPT.exists():
        print(f"[cached]  promote to MutPred-PPI.pt  (already present)")
    else:
        import shutil as _shutil
        _shutil.copy2(_ALL_DATA_CKPT_RAW, _ALL_DATA_CKPT)
        print(f"[run]     promoted {_ALL_DATA_CKPT_RAW.name} -> {_ALL_DATA_CKPT}")

    _VDB_DIR = _RESULTS_DIR / "variant_dbs_all_data"
    _VDB_STAB_DIR = _RESULTS_DIR / "variant_dbs_stability"
    for db in ("clinvar", "gnomad", "cosmic", "hgmd", "autism"):
        rows_path = DATASETS_DIR / "variant_dbs" / f"{db}_rows.csv.gz"
        if not rows_path.exists():
            print(f"[skip] {db}: {rows_path} not built (licensed data absent?)")
            continue
        cmd = [PY, "src/variant_db_inference/run_variant_db_inference.py",
              "--dataset", db, "--device", DEVICE,
              "--out", str(_VDB_DIR / f"{db}_mutpred_ppi_predictions.tsv")]
        if QUICK:
            cmd += ["--rows", str(subsample_rows(db, DB_SUBSAMPLE))]
        try:
            run(cmd, produces=[_VDB_DIR / f"{db}_mutpred_ppi_predictions.tsv"],
               name=f"run_variant_db_inference.py [{db}]")
            run([PY, "src/variant_db_inference/run_stability_inference.py",
                "--dataset", db, "--device", DEVICE, "--out-dir", str(_VDB_STAB_DIR)],
               produces=[_VDB_STAB_DIR / f"{db}_stability_predictions.tsv"],
               name=f"run_stability_inference.py [{db}]")
        except RuntimeError as exc:
            print(f"[skip] {db}: {exc}")

# %% [markdown]
# ## Step 8 -- Classification and bootstrap caches

# %%
if _VARCHAMP_AVAILABLE:
    run([PY, "src/analysis/classify_variant_dbs.py", "--output-dir", str(_VDB_DIR)],
       name="classify_variant_dbs.py")
    run([PY, "src/analysis/make_master_variant_db_csv.py"],
       produces=[_RESULTS_DIR / "master_variant_db_predictions.csv.gz"],
       name="make_master_variant_db_csv.py")
    run([PY, "src/analysis/variant_db_charts.py",
        "--data-dir", str(_VDB_DIR), "--edgotype-bootstrap", "--controlled-bootstrap",
        "--k3-only", "--n-bootstrap", str(N_BOOTSTRAP)],
       produces=[_VDB_DIR / "all_bootstrap_results.pkl"], name="variant_db_charts.py [bootstrap]")
else:
    print("[skip] Step 8: needs Step 7's variant-DB predictions.")

# %% [markdown]
# ## Step 9 -- Variant-repository figures and tables (Fig 5, S8, S9, ...)

# %%
if _VARCHAMP_AVAILABLE:
    run([PY, "src/analysis/variant_db_charts.py", "--data-dir", str(_VDB_DIR)],
       name="variant_db_charts.py [Fig 5]")
    run([PY, "src/analysis/variant_db_charts.py", "--data-dir", str(_VDB_DIR), "--controlled-k", "3"],
       name="variant_db_charts.py [S8]")
    show(_VDB_DIR / "enrichment_bootstrap_sufficient_partners.png", "Fig 5")
    show(_VDB_DIR / "enrichment_bootstrap_sufficient_partners_k3.png", "S8")

    run([PY, "src/analysis/threshold_sensitivity.py", "--n-bootstrap", str(N_BOOTSTRAP)],
       name="threshold_sensitivity.py")
    show(_RESULTS_DIR / "robustness" / "threshold_sensitivity.png", "S9")

    run([PY, "src/analysis/protein_class_enrichment.py"], name="protein_class_enrichment.py")
    show(_RESULTS_DIR / "protein_class" / "pathogenic_by_class.png", "S-protclass")

    run([PY, "src/analysis/stability_interaction_scatter.py", "--cosmic-min-recurrence", "32"],
       name="stability_interaction_scatter.py")
    show(_RESULTS_DIR / "stability_interaction" / "scatter_per_variant_kde.png", "S-stability")

    try:
        run([PY, "src/analysis/combined_robustness_figure.py"], name="combined_robustness_figure.py")
        show(_RESULTS_DIR / "robustness" / "combined_robustness_by_class.png", "S-robustness")
    except RuntimeError as exc:
        print(f"[skip] combined_robustness_figure.py: {exc}")

    run([PY, "src/analysis/cosmic_onco_tsg_stat_test.py"], name="cosmic_onco_tsg_stat_test.py")
else:
    print("[skip] Step 9 variant-DB figures: needs Step 7/8's predictions.")

if _VARCHAMP_AVAILABLE:
    run([PY, "src/analysis/generate_training_table.py"],
       produces=[REPO / "figures" / "training_data_table.tex"], name="generate_training_table.py [Table 1]")
else:
    print("[skip] Table 1: generate_training_table.py needs the unpublished "
          "VarChAMP measurements in varchamp_all_mapped090826_rows.csv.gz.")

run([PY, "src/analysis/extract_variant_db_stats.py"],
   produces=[REPO / "figures" / "variant_db_stats_table.tex"], name="extract_variant_db_stats.py [Table S1]")

for tex_name, caption in (("training_data_table.tex", "Table 1"),
                          ("variant_db_stats_table.tex", "Table S1")):
    p = REPO / "figures" / tex_name
    if p.exists():
        print(f"\n--- {caption} ({tex_name}) --- PASTE INTO THE MANUSCRIPT BY HAND (no \\input{{}}) ---")
        print(p.read_text())

# %% [markdown]
# ## Step 10 -- Manifest
#
# Every manuscript figure/table: expected path, whether it exists, and its
# age. In full (non-QUICK) mode this is where you would refresh
# `figures/*.png` symlinks if a producer's output path changed -- see
# `docs/FIGURE_INVENTORY.md` for the current map.

# %%
import datetime

_MANIFEST = [
    ("Fig 3",  _ROC_DIR / "roc_sahni_fragoza_with_variance.png"),
    ("S1",     _ROC_DIR / "roc_sahni_with_variance.png"),
    ("S3",     _ROC_DIR / "ablation_bar_sahni_fragoza_with_variance.png"),
    ("S7",     _ROC_DIR / "roc_sahni_fragoza_varchamp_all_with_variance.png"),
    ("S-biclass", _RESULTS_DIR / "biclass_gcv" / "roc_sahni_fragoza_biclass_with_variance.png"),
    ("Fig 4",  _RESULTS_DIR / "varchamp_seqcnf_newvar_eval" / "roc_plots" / "roc_varchamp_blind_test.png"),
    ("S2",     _RESULTS_DIR / "varchamp_seqcnf_newvar_eval" / "roc_plots" / "roc_varchamp_blind_test_training_comparison.png"),
    ("Fig 5",  _RESULTS_DIR / "variant_dbs_all_data" / "enrichment_bootstrap_sufficient_partners.png"),
    ("S8",     _RESULTS_DIR / "variant_dbs_all_data" / "enrichment_bootstrap_sufficient_partners_k3.png"),
    ("S9",     _RESULTS_DIR / "robustness" / "threshold_sensitivity.png"),
    ("S-protclass", _RESULTS_DIR / "protein_class" / "pathogenic_by_class.png"),
    ("S-stability", _RESULTS_DIR / "stability_interaction" / "scatter_per_variant_kde.png"),
    ("S-robustness", _RESULTS_DIR / "robustness" / "combined_robustness_by_class.png"),
    ("Table 1", REPO / "figures" / "training_data_table.tex"),
    ("Table S1", REPO / "figures" / "variant_db_stats_table.tex"),
]

print(f"{'label':<14} {'exists':<7} {'age':<12} path")
for label, path in _MANIFEST:
    exists = path.exists()
    age = (datetime.datetime.now() - datetime.datetime.fromtimestamp(path.stat().st_mtime)
          ) if exists else None
    age_str = f"{age.days}d" if age else "-"
    print(f"{label:<14} {'yes' if exists else 'NO':<7} {age_str:<12} {path}")

print("\nDrawn by hand, not regenerated by anything in this repo (docs/FIGURE_INVENTORY.md O3):")
print("  Fig 1 (MutPred-PPI_pipeline.png), Fig 2 (MutPred-PPI_architecture.png), "
      "the CDC42 example panel (CDC42_WASP_Y64.png)")
